name: ci-test

on: [push, pull_request]

jobs:
  #clj-test:
    # ubuntu 18.04 comes with lein + java8 installed
    # runs-on: ubuntu-18.04
    # steps:
    #   - name: Git checkout
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 1

    #   - name: Install bb
    #     run:
    #       ./bin/install-bb.sh

    #   - name: Install clojure tools
    #     uses: DeLaGuardo/setup-clojure@3.5
    #     with:
    #       cli: 1.10.3.943

    #   - name: Run CLJ Tests
    #     run: |
    #       bb test clj

  dummy-cljs-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y curl

      - name: Install NodeJS and Yarn
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          sudo apt-get install -y nodejs
          npm i -g yarn

      - name: Install Java
        run: |
          sudo apt-get install -y openjdk-8-jre
        
      - name: Install Clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.1040.sh &&\
          chmod +x linux-install-1.10.3.1040.sh &&\
          ./linux-install-1.10.3.1040.sh

      - name: Install Chrome
        run: |
          sudo apt-get update -qq
          sudo apt-get install -q -y xvfb libgbm1 libxss1 chromium-browser

      - name: Install cljs deps
        run: |
          npm i -g yarn
          yarn install

      - name: Run CLJS tests
        run: ./bin/ci-cljs-test.sh

  cljs-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Install bb
        run:
          ./bin/install-bb.sh

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.943

      - name: Install Chrome
        run: |
          whoami
          sudo apt-get update -qq
          sudo apt-get install -q -y xvfb libgbm1 libxss1 chromium-browser

      - name: Ensure chrome installed
        run: chromium-browser --version

      - name: Who am I??
        run: whoami 

      - name: Install cljs deps
        run: |
          npm i -g yarn
          yarn install

      - name: Run CLJS tests
        run: ./bin/ci-cljs-test.sh
